name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev
      - cicd
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint and format check
        run: |
          npx eslint . --ext ts --ext tsx --ext js
          npx prettier --check .
